safe:        true
auto:        false
server:      false
server_port: 4000
baseurl:     http://janelia-flyem.github.com
url: http://janelia-flyem.github.com

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
markdown:    kramdown
permalink:   date
lsi:         false
pygments:    true

maruku:
  use_tex:    false
  use_divs:   false

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
